memory_test.o: memory_test.c machine.h memory_test.h plugin_throughput.h \
 plugin_sequential_read.h plugin_random_read.h
plugin_random_read.o: plugin_random_read.c plugin_random_read.h machine.h
plugin_sequential_read.o: plugin_sequential_read.c \
 plugin_sequential_read.h machine.h
plugin_throughput.o: plugin_throughput.c memory_test.h \
 plugin_throughput.h machine.h plugin_sequential_read.h \
 plugin_random_read.h
