##===- callgrapher/lib/callgraphs/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.
#
LIBRARYNAME=callgraphs

CPPFLAGS += -std=c++11

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
